### ISSUE TITLE
FuncDecl double-nested type objects

### ISSUE THREAD

**Issue by marler8997** [ohjeongwook/windows_sdk_data#6]
Below is a table of module/FuncDecl pairs that contain a "double-nested" type object.  For example, instead of something like this:
```json
    {
        "data_type": "FuncDecl",
        "type": {
            "name": "AtlThunk_AllocateData",
            "type": "AtlThunkData_t"
        },
    },
```
they have this:
```json
    {
        "data_type": "FuncDecl",
        "type": {
            "type": {
                "name": "AtlThunk_AllocateData",
                "type": "AtlThunkData_t"
            }
        },
    },
```

| filename | FuncDecl |
|----------|----------|
| atlthunk.json | AtlThunk_AllocateData |
| comsvcs.json | SafeRef |
| d3d9.json | Direct3DCreate9 |
| d3d9helper.json | Direct3DCreate9 |
| inspectable.json | HSTRING_UserMarshal |
| inspectable.json | HSTRING_UserUnmarshal |
| inspectable.json | HSTRING_UserMarshal64 |
| inspectable.json | HSTRING_UserUnmarshal64 |
| mfapi.json | MFHeapAlloc |
| mscat.json | CryptCATStoreFromHandle |
| mscat.json | CryptCATPutCatAttrInfo |
| mscat.json | CryptCATEnumerateCatAttr |
| mscat.json | CryptCATGetMemberInfo |
| mscat.json | CryptCATGetAttrInfo |
| mscat.json | CryptCATPutMemberInfo |
| mscat.json | CryptCATPutAttrInfo |
| mscat.json | CryptCATEnumerateMember |
| mscat.json | CryptCATEnumerateAttr |
| mscat.json | CryptCATCDFOpen |
| mscat.json | CryptCATCDFEnumCatAttributes |
| oaidl.json | BSTR_UserMarshal |
| oaidl.json | BSTR_UserUnmarshal |
| oaidl.json | VARIANT_UserMarshal |
| oaidl.json | VARIANT_UserUnmarshal |
| oaidl.json | BSTR_UserMarshal64 |
| oaidl.json | BSTR_UserUnmarshal64 |
| oaidl.json | VARIANT_UserMarshal64 |
| oaidl.json | VARIANT_UserUnmarshal64 |
| oleauto.json | SafeArrayCreate |
| oleauto.json | SafeArrayCreateEx |
| oleauto.json | SafeArrayCreateVector |
| oleauto.json | SafeArrayCreateVectorEx |
| propidl.json | StgConvertVariantToProperty |
| remotesystemadditionalinfo.json | HSTRING_UserMarshal |
| remotesystemadditionalinfo.json | HSTRING_UserUnmarshal |
| remotesystemadditionalinfo.json | HSTRING_UserMarshal64 |
| remotesystemadditionalinfo.json | HSTRING_UserUnmarshal64 |
| rpcndr.json | NdrPointerMarshall |
| rpcndr.json | NdrSimpleStructMarshall |
| rpcndr.json | NdrComplexStructMarshall |
| rpcndr.json | NdrConformantArrayMarshall |
| rpcndr.json | NdrComplexArrayMarshall |
| rpcndr.json | NdrConformantStringMarshall |
| rpcndr.json | NdrUserMarshalMarshall |
| rpcndr.json | NdrInterfacePointerMarshall |
| rpcndr.json | NdrPointerUnmarshall |
| rpcndr.json | NdrSimpleStructUnmarshall |
| rpcndr.json | NdrComplexStructUnmarshall |
| rpcndr.json | NdrComplexArrayUnmarshall |
| rpcndr.json | NdrConformantStringUnmarshall |
| rpcndr.json | NdrUserMarshalUnmarshall |
| rpcndr.json | NdrInterfacePointerUnmarshall |
| rpcndr.json | RpcSsAllocate |
| rpcndr.json | RpcSmAllocate |
| rpcndr.json | NdrOleAllocate |
| rpcproxy.json | CStdStubBuffer_IsIIDSupported |
| shellapi.json | CommandLineToArgvW |
| shlobj_core.json | SHAlloc |
| shlobj_core.json | OpenRegStream |
| shlobj_core.json | SHFind_InitMenuPopup |
| shlwapi.json | SHOpenRegStreamA |
| shlwapi.json | SHOpenRegStreamW |
| shlwapi.json | SHOpenRegStream2A |
| shlwapi.json | SHOpenRegStream2W |
| shlwapi.json | SHCreateMemStream |
| shlwapi.json | SHLockShared |
| usp10.json | ScriptString_pSize |
| usp10.json | ScriptString_pcOutChars |
| usp10.json | ScriptString_pLogAttr |
| wia_xp.json | LPSAFEARRAY_UserMarshal |
| wia_xp.json | LPSAFEARRAY_UserUnmarshal |
| wia_xp.json | LPSAFEARRAY_UserMarshal64 |
| wia_xp.json | LPSAFEARRAY_UserUnmarshal64 |
| wincrypt.json | CertCreateContext |
| windef.json | __pctype_func |
| windef.json | __pwctype_func |
| windef.json | __acrt_get_locale_data_prefix |
| windef.json | ULongToHandle |
| windef.json | LongToHandle |
| windef.json | IntToPtr |
| windef.json | UIntToPtr |
| windef.json | LongToPtr |
| windef.json | ULongToPtr |
| windef.json | Ptr32ToPtr |
| windef.json | Handle32ToHandle |
| windef.json | PtrToPtr32 |
| windef.json | _errno |
| windef.json | __doserrno |
| windef.json | memchr |
| windef.json | memcpy |
| windef.json | memmove |
| windef.json | memset |
| windef.json | strchr |
| windef.json | strrchr |
| windef.json | strstr |
| windef.json | wcschr |
| windef.json | wcsrchr |
| windef.json | wcsstr |
| windef.json | memccpy |
| windef.json | wcstok_s |
| windef.json | _wcsdup |
| windef.json | wcscat |
| windef.json | wcscpy |
| windef.json | wcsncat |
| windef.json | wcsncpy |
| windef.json | wcspbrk |
| windef.json | wcstok |
| windef.json | _wcstok |
| windef.json | _wcserror |
| windef.json | __wcserror |
| windef.json | _wcsnset |
| windef.json | _wcsrev |
| windef.json | _wcsset |
| windef.json | _wcslwr |
| windef.json | _wcslwr_l |
| windef.json | _wcsupr |
| windef.json | _wcsupr_l |
| windef.json | wcsdup |
| windef.json | wcsnset |
| windef.json | wcsrev |
| windef.json | wcsset |
| windef.json | wcslwr |
| windef.json | wcsupr |
| windef.json | strtok_s |
| windef.json | _memccpy |
| windef.json | strcat |
| windef.json | strcpy |
| windef.json | _strdup |
| windef.json | _strerror |
| windef.json | strerror |
| windef.json | _strlwr |
| windef.json | _strlwr_l |
| windef.json | strncat |
| windef.json | strncpy |
| windef.json | _strnset |
| windef.json | strpbrk |
| windef.json | _strrev |
| windef.json | _strset |
| windef.json | strtok |
| windef.json | _strupr |
| windef.json | _strupr_l |
| windef.json | strdup |
| windef.json | strlwr |
| windef.json | strnset |
| windef.json | strrev |
| windef.json | strset |
| windef.json | strupr |
| windef.json | _exception_info |
| windef.json | NtCurrentTeb |
| winsock.json | inet_ntoa |
| winsock.json | gethostbyaddr |
| winsock.json | gethostbyname |
| winsock.json | getservbyport |
| winsock.json | getservbyname |
| winsock.json | getprotobynumber |
| winsock.json | getprotobyname |
| winsock2.json | inet_ntoa |
| winsock2.json | gethostbyaddr |
| winsock2.json | gethostbyname |
| winsock2.json | getservbyport |
| winsock2.json | getservbyname |
| winsock2.json | getprotobynumber |
| winsock2.json | getprotobyname |
| winstring.json | HSTRING_UserMarshal |
| winstring.json | HSTRING_UserUnmarshal |
| wintrust.json | WTHelperGetProvSignerFromChain |
| wintrust.json | WTHelperGetProvCertFromChain |
| wintrust.json | WTHelperProvDataFromStateData |
| wintrust.json | WTHelperGetProvPrivateDataFromChain |

**Comment by elicn** [comment]
[Sorry to bump this old one up..]
This is actually not a bug; the wrapping `type` specifies it is a pointer to the `type` defined within.
In the example you provided the function actually returns a `AtlThunkData_t*` so that is actually the intended behavior.
That is consistent across several occurences I checked manually.
